cthulhu-dreams:
  docker:
    - image: cimg/base:2022.04
  steps:
    - run:
        name: Sssssh
        command: echo "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn"

cthulhu-wakes:
  docker:
    - image: cimg/base:2022.04
  steps:
    - run:
        name: Let the world know!
        command: echo "Oh hey!"
