version: 2.1

# Dynamic configs enabled!
setup: true

orbs:
  continuation: circleci/continuation@0.3.1

workflows:
  always-ran:
    jobs:
      steps:
        - run:
          name: Generate config
          command: |
            # These two scripts will also have the task to lint and verify
            # the individual atomic CircleCI configs to print clearer messages
            # for debugging reasons
            # Note: Probably if we hash the generated yml we can cache it?
            ./config-generator.py > generated-config.yml
            ./parameters-generator.py > generated-parameters.json
        - run:
          name: Upload config to workflow artifact
          command: |
            # Here we'll upload the generated files, they can be useful
            # for debugging purpose in case of failures
            echo "Uploading generated-config.yml
            echo "Uploading generated-parameters.json
        - continuation/continue:
            config-path: ./generated-config.yml
            parameters: ./generated-parameters.json
