version: 2.1

# Dynamic configs enabled!
setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  advanced-checkout: vsco/advanced-checkout@1.0.0

jobs:
  config-generation:
    docker:
      - image: cimg/python:3.10
    steps:
      - advanced-checkout/shallow-checkout
      - run:
          name: Generate config
          command: |
            # These two scripts will also have the task to lint and verify
            # the individual atomic CircleCI configs to print clearer messages
            # for debugging reasons
            # Note: Probably if we hash the generated yml we can cache it?
            ./config_generator.py > generated-config.yml
            ./parameters_generator.py > generated-parameters.json
      - run:
          name: Upload config to workflow artifact
          command: |
            # Here we'll upload the generated files, they can be useful
            # for debugging purpose in case of failures
            echo "Uploading generated-config.yml
            echo "Uploading generated-parameters.json
      - continuation/continue:
          configuration_path: ./generated-config.yml
          parameters: ./generated-parameters.json

workflows:
  always-ran:
    jobs:
      - config-generation
